sudo: required
services:
  - docker

before_install:
  - docker build -t dockerlime/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerlime/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-187501763964"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"