sudo: required
services:
  - docker

before_install:
  - docker build -t dockerlime/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerlime/docker-react npm run test -- --watchAll=false